# Generated by Django 4.1.5 on 2023-05-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('condition', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('temperature', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('humidity', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
    ]
